export const SOCKET_INIT = 'SOCKET_INIT'
export const SOCKET_SEND_CARD = 'SOCKET_SEND_CARD'

export const SOCKET_SEND_CARDLESS = 'SOCKET_SEND_CARDLESS'
export const SOCKET_RECIEVE_TRANSDATA = 'SOCKET_RECIEVE_TRANSDATA'