export const DEPOSIT_REQUEST = 'DEPOSIT_REQUEST'
export const DEPOSIT_SUCCESS = 'DEPOSIT_SUCCESS'
export const DEPOSIT_FALIURE = 'DEPOSIT_FALIURE'
export const DEPOSIT_REQUEST_DATA = 'DEPOSIT_REQUEST_DATA'
